#define ZERO 0
#define ONE 1
#define TWO 2
#define THREE 3
#define FOUR 4
#define FIVE 5
#define SIX 6
#define SEVEN 7
#define EIGHT 8
#define NINE 9
#define TEN 10
#define ELEVEN 11
#define TWELVE 12
#define THIRTEEN 13
#define FOURTEEN 14
#define FIFTEEN 15
#define SIXTEEN 16
#define SEVENTEEN 17
#define EIGHTEEN 18
#define NINETEEN 19
#define TWENTY 20
#define TWENTYONE 21
#define TWENTYTWO 22
#define TWENTYTHREE 23
#define TWENTYFOUR 24
#define TWENTYFIVE 25
#define TWENTYSIX 26
#define TWENTYSEVEN 27
#define TWENTYEIGHT 28
#define TWENTYNINE 29
#define THIRTY 30
#define THIRTYONE 31
#define THIRTYTWO 32
#define THIRTYTHREE 33
#define THIRTYFOUR 34
#define THIRTYFIVE 35
#define THIRTYSIX 36
#define THIRTYSEVEN 37
#define THIRTYEIGHT 38
#define THIRTYNINE 39
#define FORTY 40
#define FORTYONE 41
#define FORTYTWO 42
#define FORTYTHREE 43
#define FORTYFOUR 44
#define FORTYFIVE 45
#define FORTYSIX 46
#define FORTYSEVEN 47
#define FORTYEIGHT 48
#define FORTYNINE 49
#define FIFTY 50
#define FIFTYONE 51
#define FIFTYTWO 52
#define FIFTYTHREE 53
#define FIFTYFOUR 54
